### ISSUE TITLE
db.env example(s) - update names

### ISSUE THREAD

**Issue by nishantbb** [bearlikelion/docker-compose#1]
Found a minor thing, in your firefly DB example the DB name is still nextcloud, when it should be firefly or something related?
https://github.com/bearlikelion/docker-compose/blob/master/firefly/db.env.example

Thanks for the resource.

**Comment by bearlikelion** [comment]
Thank you for bringing this up 👍🏻 
It has been changed in the latest commit, which also added photoview

https://github.com/bearlikelion/docker-compose/commit/3113c19324d36269e357224e691679cb3c6c646a
